# Generated by Django 4.2.5 on 2023-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='origin of the flight')),
                ('destination', models.CharField(max_length=50, verbose_name='destination of the flight')),
                ('duration', models.IntegerField(verbose_name='duratin of flight in mintues')),
            ],
        ),
    ]
