# Generated by Django 4.2.4 on 2023-09-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
